schemaVersion: 2.3.0
metadata:
  name: aib-rhadp-example
  tags:
    - automotive
    - rhivos
    - jumpstarter
components:
  - name: runtime
    container:
      image: quay.io/rhadp/codespaces:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
      # environment variables
      #env:
      #  - name: JUMPSTARTER_GRPC_ENDPOINT
      #    value: "jmp.svc.cluster.local:8082"
      #  - name: JUMPSTARTER_GRPC_INSECURE
      #    value: "1"
      #    value: "1"
commands:
  - id: init-workspace
    exec:
      component: runtime
      commandLine: |
        /home/tooling/.scripts/init-workspace
events:
  preStart:
    - init-workspace
