schemaVersion: 2.3.0
metadata:
  name: aib-rhadp-example
  tags:
    - automotive
    - rhivos
    - jumpstarter
components:
  - name: runtime
    container:
      image: quay.io/rhadp/codespaces:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
      # environment variables
      #env:
      #  - name: JUMPSTARTER_GRPC_ENDPOINT
      #    value: "jmp.svc.cluster.local:8082"
      #  - name: JUMPSTARTER_GRPC_INSECURE
      #    value: "1"
      #    value: "1"
commands:
  - id: configure-env-variables
    exec:
      component: runtime
      commandLine: source .env

  - id: configure-builder-client
    exec:
      component: runtime
      commandLine: |
        base64 -d /home/tooling/.ssh/privateKey > /home/tooling/.config/builder-private-key && \
        chmod 600 /home/tooling/.config/builder-private-key && \
        cp /home/tooling/.config/builder-private-key /home/user/.ssh/builder-private-key
        
  - id: configure-jumpstarter-client
    exec:
      component: runtime
      commandLine: | 
        /home/tooling/.scripts/init-jumpstarter
events:
  postStart:
    #- configure-builder-client
    #- configure-jumpstarter-client
    - configure-env-variables
